### PR TITLE
fix: Bumps go version to 1.21 (latest stable)

### PR DESCRIPTION
**Pull request by gatici**
This project currently uses Go 1.16 which is end of life. This PR bumps the go version to 1.21 which is the latest stable release. 

The update is accomplished by running following commands:
```
go mod edit -go=1.21
go mod tidy
```

Reference: https://tip.golang.org/doc/go1.21

### CODE REVIEW

**Review by gab-arrobo — APPROVED** [review]
+1

**Comment by gab-arrobo** [comment]
@gatici, how are you planning to use this repo? During today's TST meeting, it was indicated that this repo is only used for P4-based UPF

**Comment by gatici** [comment]
> @gatici, how are you planning to use this repo? During today's TST meeting, it was indicated that this repo is only used for P4-based UPF

We are not planning to use it at the moment. However, I  saw that repo also requires to use latest stable as well, and created the PR.

**Comment by gab-arrobo** [comment]
> > @gatici, how are you planning to use this repo? During today's TST meeting, it was indicated that this repo is only used for P4-based UPF
> 
> We are not planning to use it at the moment. However, I saw that repo also requires to use latest stable as well, and created the PR.

Well, I am not going to be able to approve (and/or merge) this PR because I do not have permissions to do so.

I would recommend to close this PR and re-open it if/when you need to use this repo

**Comment by gatici** [comment]
> > > @gatici, how are you planning to use this repo? During today's TST meeting, it was indicated that this repo is only used for P4-based UPF
> > 
> > 
> > We are not planning to use it at the moment. However, I saw that repo also requires to use latest stable as well, and created the PR.
> 
> Well, I am not going to be able to approve (and/or merge) this PR because I do not have permissions to do so.
> 
> I would recommend to close this PR and re-open it if/when you need to use this repo

Thank you @gab-arrobo. I will close the PR now.

**Pull request closed without merging**
